export const appConfig = Object.freeze({
  baseUrl: process.env.BASE_URL,
  port: process.env.PORT,
  release: process.env.RELEASE,
  jwtSecret: process.env.SECRET,
  otpSecret: process.env.OTPSEC,
  appDb: process.env.DB_CONNECTOR,
  smtpHost: process.env.SMTP_HOST,
  smtpPort: process.env.SMTP_PORT,
  smtpUser: process.env.SMTP_USER,
  smtpPass: process.env.SMTP_PASS,
  smtpFrom: process.env.SMTP_FROM,
  googleClientId: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
});
