export const appConfig = Object.freeze({
  baseUrl: process.env.BASE_URL,
  port: process.env.PORT,
  release: process.env.RELEASE,
  otpSecret: process.env.OTPSEC,
  appDb: process.env.DB_CONNECTOR,
  smtpHost: process.env.SMTP_HOST,
  smtpPort: process.env.SMTP_PORT,
  smtpUser: process.env.SMTP_USER,
  smtpPass: process.env.SMTP_PASS,
  smtpSender: process.env.SMTP_SENDER,
  googleClientId: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  vectorDbUrl: process.env.VECTOR_DB_URL,
  jwksUri: process.env.JWKS_URI,
  semanticValue: process.env.SEMANTIC_VALUE,
  vectorValue: process.env.VECTOR_VALUE,
  positionValue: process.env.POSITION_VALUE,
  topkValue: process.env.TOPK_VALUE,
  aiModel: process.env.AI_MODEL,
  embedModel: process.env.EMBED_MODEL,
  maxChunkSize: process.env.MAX_CHUNK_SIZE,
  maxOverlaps: process.env.MAX_OVERLAPS,
});
